project 'KFDataTests'
workspace '../KFData'
inhibit_all_warnings!
use_frameworks!

abstract_target 'KFData' do
  pod 'QueryKit'
  pod 'KFData', :path => '../'
  pod 'KFData/Compatibility', :path => '../'
  pod 'Expecta'

  target 'iOS Tests' do
    platform :ios, '8.0'
  end

  target 'OS X Tests' do
    platform :osx, '10.7'
  end
end
