xcodeproj 'KFDataTests'
workspace '../KFData'
inhibit_all_warnings!
use_frameworks!

def import_pods
    pod 'QueryKit'
    pod 'KFData', :path => '../'
    pod 'KFData/Compatibility', :path => '../'
    pod 'Expecta'
end

target :ios do
    platform :ios, '8.0'
    link_with 'iOS Tests'
    import_pods
end

target :osx do
    platform :osx, '10.7'
    link_with 'OS X Tests'
    import_pods
end

